repos:
  # Miscellaneous checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
#      - id: check-json
      - id: check-yaml
        args: ["--unsafe"]
#      - id: pretty-format-json
#        args:
#          - --no-ensure-ascii
#          - --autofix

  # isort alphabetizes your python imports and groups them
  # The 'black' profile helps us avoid disagreements with the blue formatter.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
        args:
          - -l=120
          - --py=39
          - --profile=black
          - --filter-files
          - --skip-gitignore

  # blue auto-formats python files for us
  - repo: https://github.com/grantjenks/blue.git
    rev: v0.9.1
    hooks:
      - id: blue
        types: [python]
        args:
          - -l120
          - -tpy39
          - --exclude="(\.gitlab)"

  # pydocstyle checks docstring styles after blue is done reformatting
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        types: [python]
        exclude: '^.*/migrations/.*$|test_.+\.py'
        args:
          - --config=.pydocstyle

  # After blue is done reformatting everything, double check it with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        types: [python]
        args:
          - --max-line-length=120
          - --extend-ignore=E203

  # mypy validates the python typing as per PEP 484
  # See https://jaredkhan.com/blog/mypy-pre-commit for the source of this
  # - repo: local
  #    # We do not use pre-commit/mirrors-mypy,
  #    # as it comes with opinionated defaults
  #    # (like --ignore-missing-imports)
  #    # and is difficult to configure to run
  #    # with the dependencies correctly installed.
  #    hooks:
  #      - id: mypy
  #        name: mypy
  #        entry: "./scripts/run-mypy"
  #        # A script hook uses the active virtual environment, so it must be up-to-date with `poetry install --sync`
  #        language: script
  #        types_or: [python, toml]
  #        # use require_serial so that script
  #        # is only called once per commit
  #        require_serial: true
  #        # Print the number of files as a sanity-check
  #        verbose: true
